//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/TouchpadTouchActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchpadTouchActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchpadTouchActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchpadTouchActions"",
    ""maps"": [
        {
            ""name"": ""LeftController"",
            ""id"": ""6d4629dd-6e5f-417c-bea8-e58d656a0377"",
            ""actions"": [
                {
                    ""name"": ""ThumbTouched"",
                    ""type"": ""Button"",
                    ""id"": ""de376d65-c48f-4ed9-b5df-5775be0b7786"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""edf5cca6-d7f4-4542-935b-3cfd0356995d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whiteboard_Clear"",
                    ""type"": ""Button"",
                    ""id"": ""171590dd-6929-4384-b6fe-4f6a9c515a0a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9891e417-f4aa-4818-bcfb-ac8056954644"",
                    ""path"": ""<XRController>{LeftHand}/thumbrestTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""003985df-5cae-4d9b-9762-a0f3194d3434"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8172ac5-3e1a-44f8-8bb2-01eb45668e23"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53311943-6bdf-4c71-9804-f2939c48edde"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6dd01e0-9ec1-4ff1-934f-f3ab59aee23e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9275ffb2-1ad7-4652-8dbc-ab0179bb1443"",
                    ""path"": ""<XRController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53784b91-1adb-4310-80db-141825fac347"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deed7e20-6bec-4433-a5a7-adac221662e3"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89dd2f5e-8493-4a51-9380-714436030263"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whiteboard_Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c1a981d-d9d7-4513-a111-aad055010e1c"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whiteboard_Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightController"",
            ""id"": ""0f1d522d-c6a3-4e1c-962d-0d78d73a855c"",
            ""actions"": [
                {
                    ""name"": ""ThumbTouched"",
                    ""type"": ""Button"",
                    ""id"": ""fa484675-2d36-4a13-8a7a-d9dd699cf223"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9914cfa6-ed94-4b18-a605-aba8c47d1599"",
                    ""path"": ""<XRController>{RightHand}/thumbrestTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9738de99-0401-4f70-9c80-757cce8bec30"",
                    ""path"": ""<XRController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0c1b492-7013-4005-8620-edf6dfe19bb8"",
                    ""path"": ""<XRController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f471e192-1c4a-4026-90ad-66ffd7f8e2c5"",
                    ""path"": ""<XRController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LeftController
        m_LeftController = asset.FindActionMap("LeftController", throwIfNotFound: true);
        m_LeftController_ThumbTouched = m_LeftController.FindAction("ThumbTouched", throwIfNotFound: true);
        m_LeftController_Menu = m_LeftController.FindAction("Menu", throwIfNotFound: true);
        m_LeftController_Whiteboard_Clear = m_LeftController.FindAction("Whiteboard_Clear", throwIfNotFound: true);
        // RightController
        m_RightController = asset.FindActionMap("RightController", throwIfNotFound: true);
        m_RightController_ThumbTouched = m_RightController.FindAction("ThumbTouched", throwIfNotFound: true);
    }

    ~@TouchpadTouchActions()
    {
        UnityEngine.Debug.Assert(!m_LeftController.enabled, "This will cause a leak and performance issues, TouchpadTouchActions.LeftController.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_RightController.enabled, "This will cause a leak and performance issues, TouchpadTouchActions.RightController.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LeftController
    private readonly InputActionMap m_LeftController;
    private List<ILeftControllerActions> m_LeftControllerActionsCallbackInterfaces = new List<ILeftControllerActions>();
    private readonly InputAction m_LeftController_ThumbTouched;
    private readonly InputAction m_LeftController_Menu;
    private readonly InputAction m_LeftController_Whiteboard_Clear;
    public struct LeftControllerActions
    {
        private @TouchpadTouchActions m_Wrapper;
        public LeftControllerActions(@TouchpadTouchActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThumbTouched => m_Wrapper.m_LeftController_ThumbTouched;
        public InputAction @Menu => m_Wrapper.m_LeftController_Menu;
        public InputAction @Whiteboard_Clear => m_Wrapper.m_LeftController_Whiteboard_Clear;
        public InputActionMap Get() { return m_Wrapper.m_LeftController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftControllerActions set) { return set.Get(); }
        public void AddCallbacks(ILeftControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftControllerActionsCallbackInterfaces.Add(instance);
            @ThumbTouched.started += instance.OnThumbTouched;
            @ThumbTouched.performed += instance.OnThumbTouched;
            @ThumbTouched.canceled += instance.OnThumbTouched;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Whiteboard_Clear.started += instance.OnWhiteboard_Clear;
            @Whiteboard_Clear.performed += instance.OnWhiteboard_Clear;
            @Whiteboard_Clear.canceled += instance.OnWhiteboard_Clear;
        }

        private void UnregisterCallbacks(ILeftControllerActions instance)
        {
            @ThumbTouched.started -= instance.OnThumbTouched;
            @ThumbTouched.performed -= instance.OnThumbTouched;
            @ThumbTouched.canceled -= instance.OnThumbTouched;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Whiteboard_Clear.started -= instance.OnWhiteboard_Clear;
            @Whiteboard_Clear.performed -= instance.OnWhiteboard_Clear;
            @Whiteboard_Clear.canceled -= instance.OnWhiteboard_Clear;
        }

        public void RemoveCallbacks(ILeftControllerActions instance)
        {
            if (m_Wrapper.m_LeftControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftControllerActions @LeftController => new LeftControllerActions(this);

    // RightController
    private readonly InputActionMap m_RightController;
    private List<IRightControllerActions> m_RightControllerActionsCallbackInterfaces = new List<IRightControllerActions>();
    private readonly InputAction m_RightController_ThumbTouched;
    public struct RightControllerActions
    {
        private @TouchpadTouchActions m_Wrapper;
        public RightControllerActions(@TouchpadTouchActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThumbTouched => m_Wrapper.m_RightController_ThumbTouched;
        public InputActionMap Get() { return m_Wrapper.m_RightController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightControllerActions set) { return set.Get(); }
        public void AddCallbacks(IRightControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_RightControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightControllerActionsCallbackInterfaces.Add(instance);
            @ThumbTouched.started += instance.OnThumbTouched;
            @ThumbTouched.performed += instance.OnThumbTouched;
            @ThumbTouched.canceled += instance.OnThumbTouched;
        }

        private void UnregisterCallbacks(IRightControllerActions instance)
        {
            @ThumbTouched.started -= instance.OnThumbTouched;
            @ThumbTouched.performed -= instance.OnThumbTouched;
            @ThumbTouched.canceled -= instance.OnThumbTouched;
        }

        public void RemoveCallbacks(IRightControllerActions instance)
        {
            if (m_Wrapper.m_RightControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_RightControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightControllerActions @RightController => new RightControllerActions(this);
    public interface ILeftControllerActions
    {
        void OnThumbTouched(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnWhiteboard_Clear(InputAction.CallbackContext context);
    }
    public interface IRightControllerActions
    {
        void OnThumbTouched(InputAction.CallbackContext context);
    }
}
